ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


CREATE USER SEMI2ND IDENTIFIED BY SEMI2ND;


GRANT RESOURCE, CONNECT TO SEMI2ND;


ALTER USER SEMI2ND DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;


------------------------------------------------------------------------------------


CREATE TABLE "MEMBER_GRADE"(
	MEMBER_GRADE NUMBER PRIMARY KEY,
	GRADE_NAME VARCHAR2(30) NOT NULL
);


--INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO1.NEXTVAL, ?, ?, ?, DEFAULT, DEFAULT, 44);

INSERT INTO MEMBER_GRADE VALUES(44, '일반');
INSERT INTO MEMBER_GRADE VALUES(55, '특별');

SELECT * FROM MEMBER;
SELECT * FROM PRACTiCE;
ROLLBACK;

CREATE TABLE "MEMBER" (
	"MEMBER_NO" NUMBER PRIMARY KEY,
	"MEMBER_ID" VARCHAR2(50) ,
	"MEMBER_PW" VARCHAR2(100) ,
	"MEMBER_NICKNAME" VARCHAR2(30),
	"ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL,
	"MEMBER_GRADE" NUMBER NOT NULL CONSTRAINT GRADE_CODE_FK REFERENCES "MEMBER_GRADE"
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';
COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부(N:탈퇴X, Y: 탈퇴O)';
COMMENT ON COLUMN "MEMBER"."MEMBER_GRADE" IS '회원 등급';

COMMIT;

DROP TABLE MEMBER CASCADE CONSTRAINT;
--DROP TABLE PRACTICE CASCADE CONSTRAINT;

ALTER TABLE "MEMBER" ADD CONSTRAINT "CH_MEMBER_DEL_FL" 
CHECK("MEMBER_DEL_FL" IN ('N', 'Y'));

CREATE SEQUENCE SEQ_MEMBER_NO1 NOCACHE;

DROP SEQUENCE SEQ_MEMBER_NO1;

INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO1.NEXTVAL, 'user01', 'pass01','첫번째회원', DEFAULT, DEFAULT, 44);

INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO1.NEXTVAL, 'user02', 'pass02','두번째회원', DEFAULT, DEFAULT, 55);

INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO1.NEXTVAL, 'user03', 'pass03','세번째회원', DEFAULT, DEFAULT, 44);
COMMIT;

CREATE TABLE "PRACTICE"(
	"PRACTICE_NO" NUMBER NOT NULL,
	"PRACTICE_TITLE" VARCHAR2(100) NOT NULL,
	"PRACTICE_MEMO" VARCHAR(300),
	"PRACTICE_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"PRACTICE_COMPLETE" CHAR(1) DEFAULT 'N' NOT NULL,
	"MEMBER_NO" NUMBER CONSTRAINT MEMBER_NO_FK REFERENCES "MEMBER"
);


COMMENT ON COLUMN "PRACTICE"."PRACTICE_NO" IS '연습 과목번호';
COMMENT ON COLUMN "PRACTICE"."PRACTICE_TITLE" IS '연습 과목';
COMMENT ON COLUMN "PRACTICE"."PRACTICE_MEMO" IS '연습 내용';
COMMENT ON COLUMN "PRACTICE"."PRACTICE_DATE" IS '연습 날짜';
COMMENT ON COLUMN "PRACTICE"."PRACTICE_COMPLETE" IS '완료 여부';
COMMENT ON COLUMN "PRACTICE"."MEMBER_NO" IS '작성 회원 번호';


CREATE SEQUENCE SEQ_PRACTICE_NO NOCACHE;
ALTER TABLE "PRACTICE" ADD CONSTRAINT "PK_PRACTICE" PRIMARY KEY ("PRACTICE_NO");


INSERT INTO "PRACTICE"
VALUES (SEQ_PRACTICE_NO.NEXTVAL, '카버보드 타기', '속도 내는 연습하기', DEFAULT, DEFAULT, 1);
COMMIT;

SELECT *
FROM PRACTICE;